import realEstateImg from './images/real_estate.png'
import constructionImg from './images/construction.png'
import businessImg from './images/business.png'
import marketingImg from './images/marketing.png'
import financeImg from './images/finance.png'
import technologyImg from './images/technology.png'
import designImg from './images/design.png'

export interface LearnTab {
  key: string
  label: string
  color: string
}


const TAB_COLOR = '#6B7280'; 

export const LEARN_TABS: LearnTab[] = [
  { key: 'all', label: 'All', color: TAB_COLOR },
  { key: 'real-estate', label: 'Real Estate', color: TAB_COLOR },
  { key: 'construction', label: 'Construction', color: TAB_COLOR },
  { key: 'business', label: 'Business', color: TAB_COLOR },
  { key: 'marketing', label: 'Marketing', color: TAB_COLOR },
  { key: 'finance', label: 'Finance', color: TAB_COLOR },
  { key: 'technology', label: 'Technology', color: TAB_COLOR },
  { key: 'design', label: 'Design', color: TAB_COLOR },
];

export interface Course {
  id: string
  title: string
  description: string
  category: string
  lessons: number
  duration: string
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced'
  progress: number
  image: string
  isFeatured?: boolean
}

export const COURSES: Course[] = [
  {
    id: 'c-1',
    title: 'Real Estate Fundamentals',
    description: 'Learn the basics of real estate, property types, and market dynamics.',
    category: 'real-estate',
    lessons: 12,
    duration: '3h 45m',
    difficulty: 'Intermediate',
    progress: 75,
    image: realEstateImg,
    isFeatured: true,
  },

  {
    id: 'c-3',
    title: 'Building Design & Planning',
    description: 'Understand architectural planning, space optimization and design principles.',
    category: 'design',
    lessons: 10,
    duration: '2h 30m',
    difficulty: 'Beginner',
    progress: 20,
    image: designImg,
  },
  {
    id: 'c-4',
    title: 'Real Estate Investment Strategies',
    description: 'Explore investment options, risk analysis and maximizing ROI.',
    category: 'real-estate',
    lessons: 14,
    duration: '3h 15m',
    difficulty: 'Advanced',
    progress: 60,
    image: realEstateImg,
  },

  {
    id: 'c-6',
    title: 'Digital Marketing for Property',
    description: 'Leverage social media, SEO, and paid ads to generate highly qualified leads.',
    category: 'marketing',
    lessons: 18,
    duration: '5h 00m',
    difficulty: 'Intermediate',
    progress: 10,
    image: marketingImg,
    isFeatured: true,
  },
  {
    id: 'c-7',
    title: 'Property Valuation & Finance',
    description: 'Learn how to accurately value properties and secure funding for developments.',
    category: 'finance',
    lessons: 22,
    duration: '6h 15m',
    difficulty: 'Advanced',
    progress: 0,
    image: financeImg,
  },
  {
    id: 'c-8',
    title: 'Smart Home Technology Trends',
    description: 'Discover the latest IoT devices and automation systems for modern properties.',
    category: 'technology',
    lessons: 6,
    duration: '1h 45m',
    difficulty: 'Beginner',
    progress: 100,
    image: technologyImg,
  },
  {
    id: 'c-9',
    title: 'Corporate Finance Basics',
    description: 'A comprehensive guide to financial statements, accounting, and corporate modeling.',
    category: 'finance',
    lessons: 11,
    duration: '4h 00m',
    difficulty: 'Intermediate',
    progress: 50,
    image: financeImg,
  },

  {
    id: 'c-11',
    title: 'Introduction to Data Analytics',
    description: 'Harness the power of big data to make informed property and business decisions.',
    category: 'technology',
    lessons: 14,
    duration: '4h 30m',
    difficulty: 'Beginner',
    progress: 0,
    image: technologyImg,
  },
  {
    id: 'c-12',
    title: 'UI/UX Principles for Real Estate Apps',
    description: 'Design intuitive interfaces for property listing platforms and CRMs.',
    category: 'design',
    lessons: 16,
    duration: '5h 15m',
    difficulty: 'Intermediate',
    progress: 15,
    image: designImg,
    isFeatured: true,
  },
  {
    id: 'c-13',
    title: 'Leadership & Team Dynamics',
    description: 'Develop leadership skills to manage construction and brokerage teams effectively.',
    category: 'business',
    lessons: 10,
    duration: '3h 00m',
    difficulty: 'Intermediate',
    progress: 85,
    image: businessImg,
  },
  {
    id: 'c-14',
    title: 'Content Strategy Mastery',
    description: 'Create engaging content to build brand authority in competitive markets.',
    category: 'marketing',
    lessons: 12,
    duration: '3h 45m',
    difficulty: 'Beginner',
    progress: 45,
    image: marketingImg,
  },
  {
    id: 'c-15',
    title: 'Property Management 101',
    description: 'Learn tenant relations, maintenance scheduling, and rent collection laws.',
    category: 'real-estate',
    lessons: 20,
    duration: '6h 30m',
    difficulty: 'Beginner',
    progress: 100,
    image: realEstateImg,
  },
  {
    id: 'c-16',
    title: 'Sustainable Building Materials',
    description: 'Explore eco-friendly materials and LEED certification requirements.',
    category: 'construction',
    lessons: 8,
    duration: '2h 20m',
    difficulty: 'Advanced',
    progress: 0,
    image: constructionImg,
  },
  {
    id: 'c-17',
    title: 'Personal Wealth Building',
    description: 'Strategies for diversifying income streams through property and stocks.',
    category: 'finance',
    lessons: 15,
    duration: '4h 10m',
    difficulty: 'Intermediate',
    progress: 60,
    image: financeImg,
  },
  {
    id: 'c-18',
    title: 'Cloud Computing Essentials',
    description: 'Migrate your business operations to scalable cloud infrastructures.',
    category: 'technology',
    lessons: 11,
    duration: '3h 50m',
    difficulty: 'Intermediate',
    progress: 10,
    image: technologyImg,
  },
  {
    id: 'c-19',
    title: 'Interior Design Fundamentals',
    description: 'Master color theory, lighting, and staging to increase property appeal.',
    category: 'design',
    lessons: 9,
    duration: '2h 40m',
    difficulty: 'Beginner',
    progress: 25,
    image: designImg,
  },
  {
    id: 'c-20',
    title: 'Entrepreneurship & Startup Basics',
    description: 'From business plan to seed funding: launch your real estate tech startup.',
    category: 'business',
    lessons: 24,
    duration: '8h 00m',
    difficulty: 'Advanced',
    progress: 5,
    image: businessImg,
    isFeatured: true,
  },
  {
    id: 'c-21',
    title: 'Email Marketing Automation',
    description: 'Set up drip campaigns to nurture leads and convert prospects automatically.',
    category: 'marketing',
    lessons: 7,
    duration: '2h 00m',
    difficulty: 'Intermediate',
    progress: 90,
    image: marketingImg,
  },
  {
    id: 'c-22',
    title: 'Commercial Leasing',
    description: 'Understand triple net leases, tenant improvements, and commercial clauses.',
    category: 'real-estate',
    lessons: 13,
    duration: '4h 15m',
    difficulty: 'Advanced',
    progress: 0,
    image: realEstateImg,
  },
  {
    id: 'c-23',
    title: 'Heavy Machinery Operations',
    description: 'Safety protocols and operational basics for site excavation and lifting.',
    category: 'construction',
    lessons: 18,
    duration: '5h 30m',
    difficulty: 'Intermediate',
    progress: 30,
    image: constructionImg,
  },
  {
    id: 'c-24',
    title: 'Real Estate Blockchain Basics',
    description: 'How smart contracts and tokenization are changing property transactions.',
    category: 'finance',
    lessons: 6,
    duration: '1h 50m',
    difficulty: 'Advanced',
    progress: 100,
    image: financeImg,
  },
  {
    id: 'c-25',
    title: 'Cybersecurity Fundamentals',
    description: 'Protect sensitive client data and financial records from cyber threats.',
    category: 'technology',
    lessons: 12,
    duration: '3h 25m',
    difficulty: 'Beginner',
    progress: 50,
    image: technologyImg,
  },
  {
    id: 'c-26',
    title: '3D Modeling with Blender',
    description: 'Create photorealistic architectural renders and virtual walkthroughs.',
    category: 'design',
    lessons: 25,
    duration: '9h 15m',
    difficulty: 'Advanced',
    progress: 12,
    image: designImg,
  },
  {
    id: 'c-27',
    title: 'Agile Project Management',
    description: 'Apply agile methodologies to keep complex projects on time and under budget.',
    category: 'business',
    lessons: 14,
    duration: '4h 00m',
    difficulty: 'Intermediate',
    progress: 75,
    image: businessImg,
    isFeatured: true,
  },
  {
    id: 'c-28',
    title: 'Brand Identity & Positioning',
    description: 'Craft a compelling visual identity and voice for your agency or firm.',
    category: 'marketing',
    lessons: 9,
    duration: '2h 45m',
    difficulty: 'Beginner',
    progress: 0,
    image: marketingImg,
  },
  {
    id: 'c-29',
    title: 'International Real Estate Markets',
    description: 'Analyzing global trends, cross-border investments, and foreign regulations.',
    category: 'real-estate',
    lessons: 16,
    duration: '5h 20m',
    difficulty: 'Advanced',
    progress: 20,
    image: realEstateImg,
  },
  {
    id: 'c-30',
    title: 'Advanced Blueprint Reading',
    description: 'Deep dive into structural, electrical, and plumbing schematics.',
    category: 'construction',
    lessons: 11,
    duration: '3h 10m',
    difficulty: 'Intermediate',
    progress: 65,
    image: constructionImg,
  }
]