import thumb1 from './podcasts/thumb_1.png'
import thumb2 from './podcasts/thumb_2.png'
import thumb3 from './podcasts/thumb_3.png'
import thumb4 from './podcasts/thumb_4.png'
import thumb5 from './podcasts/thumb_5.png'
import thumb6 from './podcasts/thumb_6.png'

export interface TabType {
  key: string
  label: string
  color?: string
  count?: number
}

const TAB_COLOR = '#6B7280'

export const FILTER_TABS: TabType[] = [
  { key: 'all', label: 'All', color: TAB_COLOR },
  { key: 'interviews', label: 'Interviews', color: TAB_COLOR },
  { key: 'tech', label: 'Technology', color: TAB_COLOR },
  { key: 'business', label: 'Business', color: TAB_COLOR },
  { key: 'news', label: 'News & Politics', color: TAB_COLOR },
  { key: 'education', label: 'Education', color: TAB_COLOR },
  { key: 'comedy', label: 'Comedy', color: TAB_COLOR }, 
  { key: 'true-crime', label: 'True Crime', color: TAB_COLOR },
  { key: 'health', label: 'Health & Fitness', color: TAB_COLOR },
]

export interface PodcastEpisode {
  id: string
  title: string
  speaker: string
  role: string
  duration: string
  listens: string
  timeAgo: string
  thumbnail: string
  category: string
  verified: boolean
}

export const PODCAST_EPISODES: PodcastEpisode[] = [
  {
    id: 'pe-1',
    title: 'How to Build a Personal Brand That Attracts Clients',
    speaker: 'Karan Malhotra',
    role: 'Brand Strategist',
    duration: '32:45',
    listens: '12.4K listens',
    timeAgo: '2 days ago',
    thumbnail: thumb1,
    category: 'business', 
    verified: true,
  },
  {
    id: 'pe-2',
    title: 'The Future of AI: What to Expect in 2027',
    speaker: 'Ritika Sharma',
    role: 'Tech Analyst',
    duration: '28:10',
    listens: '19.8K listens',
    timeAgo: '3 days ago',
    thumbnail: thumb2,
    category: 'tech',
    verified: true,
  },
  {
    id: 'pe-3',
    title: 'Sit-down with the Founder of NextGen Logistics',
    speaker: 'Amit Verma',
    role: 'Journalist',
    duration: '45:30',
    listens: '8.2K listens',
    timeAgo: '5 days ago',
    thumbnail: thumb3,
    category: 'interviews',
    verified: true,
  },
  {
    id: 'pe-4',
    title: 'Global Market Shifts & Policy Changes This Week',
    speaker: 'Nikhil Gupta',
    role: 'Political Commentator',
    duration: '29:15',
    listens: '7.6K listens',
    timeAgo: '1 week ago',
    thumbnail: thumb4,
    category: 'news',
    verified: false,
  },
  {
    id: 'pe-5',
    title: 'The Psychology of Learning: Retaining Information',
    speaker: 'Neha Iyer',
    role: 'Cognitive Scientist',
    duration: '27:40',
    listens: '15.3K listens',
    timeAgo: '1 week ago',
    thumbnail: thumb5,
    category: 'education',
    verified: true,
  },
  {
    id: 'pe-6',
    title: 'Optimizing Your Circadian Rhythm for Productivity',
    speaker: 'Rahul Prasad',
    role: 'Health Expert',
    duration: '22:18',
    listens: '11.2K listens',
    timeAgo: '1 week ago',
    thumbnail: thumb6,
    category: 'health',
    verified: true,
  },
  {
    id: 'pe-7',
    title: 'The Silicon Valley Startup Heist of 2018',
    speaker: 'Sarah Jenkins',
    role: 'Investigative Reporter',
    duration: '52:10',
    listens: '34.5K listens',
    timeAgo: '2 weeks ago',
    thumbnail: thumb1, 
    category: 'true-crime',
    verified: true,
  },
  {
    id: 'pe-8',
    title: 'Scaling from $1M to $10M ARR',
    speaker: 'David Chen',
    role: 'Venture Capitalist',
    duration: '38:45',
    listens: '22.1K listens',
    timeAgo: '2 weeks ago',
    thumbnail: thumb2, 
    category: 'business',
    verified: true,
  },
  {
    id: 'pe-9',
    title: 'Understanding Quantum Computing Basics',
    speaker: 'Dr. Elena Rostova',
    role: 'Quantum Physicist',
    duration: '41:20',
    listens: '14.9K listens',
    timeAgo: '3 weeks ago',
    thumbnail: thumb3, 
    category: 'tech',
    verified: true,
  },
  {
    id: 'pe-10',
    title: 'Deep Dive: Inside the Mind of a Top CEO',
    speaker: 'Marcus Thorne',
    role: 'Executive Coach',
    duration: '55:00',
    listens: '28.4K listens',
    timeAgo: '1 month ago',
    thumbnail: thumb4, 
    category: 'interviews',
    verified: true,
  },
  {
    id: 'pe-11',
    title: 'Why My Dog is a Better Manager Than Me',
    speaker: 'Chris Evans',
    role: 'Comedian & Writer',
    duration: '24:15',
    listens: '45.2K listens',
    timeAgo: '1 month ago',
    thumbnail: thumb5,
    category: 'comedy',
    verified: true,
  },
  {
    id: 'pe-12',
    title: 'The History of Ancient Trade Routes',
    speaker: 'Dr. Alistair Vance',
    role: 'Historian',
    duration: '48:10',
    listens: '9.3K listens',
    timeAgo: '1 month ago',
    thumbnail: thumb6,
    category: 'education',
    verified: false,
  },
  {
    id: 'pe-13',
    title: 'Navigating Mental Health in High-Stress Jobs',
    speaker: 'Dr. Priya Desai',
    role: 'Psychiatrist',
    duration: '39:50',
    listens: '31.8K listens',
    timeAgo: '1 month ago',
    thumbnail: thumb1,
    category: 'health',
    verified: true,
  },
  {
    id: 'pe-14',
    title: 'Web3 and the Future of Digital Ownership',
    speaker: 'Alex Turner',
    role: 'Blockchain Developer',
    duration: '44:25',
    listens: '18.5K listens',
    timeAgo: '2 months ago',
    thumbnail: thumb2,
    category: 'tech',
    verified: true,
  },
  {
    id: 'pe-15',
    title: 'Bootstrapping vs. VC Funding: Making the Choice',
    speaker: 'Samantha Lee',
    role: 'Serial Entrepreneur',
    duration: '35:40',
    listens: '21.1K listens',
    timeAgo: '2 months ago',
    thumbnail: thumb3,
    category: 'business',
    verified: true,
  },
  {
    id: 'pe-16',
    title: 'Election Year Impacts on Local Economies',
    speaker: 'Robert King',
    role: 'Economist',
    duration: '51:15',
    listens: '13.2K listens',
    timeAgo: '2 months ago',
    thumbnail: thumb4,
    category: 'news',
    verified: true,
  },
  {
    id: 'pe-17',
    title: 'The Mystery of the Vanishing Artwork',
    speaker: 'Jessica Cho',
    role: 'Art Detective',
    duration: '47:30',
    listens: '55.9K listens',
    timeAgo: '2 months ago',
    thumbnail: thumb5,
    category: 'true-crime',
    verified: true,
  },
  {
    id: 'pe-18',
    title: 'A Conversation with the Architect of Tomorrow',
    speaker: 'Liam O’Connor',
    role: 'Urban Planner',
    duration: '58:20',
    listens: '16.7K listens',
    timeAgo: '3 months ago',
    thumbnail: thumb6,
    category: 'interviews',
    verified: false,
  },
  {
    id: 'pe-19',
    title: 'Surviving the Office Holiday Party',
    speaker: 'Mindy K.',
    role: 'Stand-up Comedian',
    duration: '21:05',
    listens: '89.4K listens',
    timeAgo: '3 months ago',
    thumbnail: thumb1,
    category: 'comedy',
    verified: true,
  },
  {
    id: 'pe-20',
    title: 'Demystifying Calculus for Beginners',
    speaker: 'Prof. John Davies',
    role: 'Mathematics Educator',
    duration: '33:15',
    listens: '24.6K listens',
    timeAgo: '3 months ago',
    thumbnail: thumb2,
    category: 'education',
    verified: true,
  },
  {
    id: 'pe-21',
    title: 'The Gut Microbiome and Your Mood',
    speaker: 'Anita Patel',
    role: 'Clinical Nutritionist',
    duration: '42:10',
    listens: '41.3K listens',
    timeAgo: '4 months ago',
    thumbnail: thumb3,
    category: 'health',
    verified: true,
  },
  {
    id: 'pe-22',
    title: 'Cybersecurity in the Age of Smart Homes',
    speaker: 'David Black',
    role: 'Security Analyst',
    duration: '37:55',
    listens: '17.8K listens',
    timeAgo: '4 months ago',
    thumbnail: thumb4,
    category: 'tech',
    verified: true,
  },
  {
    id: 'pe-23',
    title: 'Building a Resilient Global Supply Chain',
    speaker: 'Wei Chen',
    role: 'Operations Director',
    duration: '49:30',
    listens: '11.5K listens',
    timeAgo: '4 months ago',
    thumbnail: thumb5,
    category: 'business',
    verified: false,
  },
  {
    id: 'pe-24',
    title: 'European Energy Crisis: A Deep Dive',
    speaker: 'Elena Rostova',
    role: 'Geopolitical Analyst',
    duration: '54:15',
    listens: '22.9K listens',
    timeAgo: '5 months ago',
    thumbnail: thumb6,
    category: 'news',
    verified: true,
  },
  {
    id: 'pe-25',
    title: 'Cyber Heist: The Billion Dollar Hack',
    speaker: 'Kevin Mason',
    role: 'Tech Journalist',
    duration: '62:40',
    listens: '78.1K listens',
    timeAgo: '5 months ago',
    thumbnail: thumb1,
    category: 'true-crime',
    verified: true,
  },
  {
    id: 'pe-26',
    title: 'Finding Peace in Chaos with a Zen Master',
    speaker: 'Thich Nhat',
    role: 'Author & Monk',
    duration: '45:00',
    listens: '92.4K listens',
    timeAgo: '6 months ago',
    thumbnail: thumb2,
    category: 'interviews',
    verified: true,
  },
  {
    id: 'pe-27',
    title: 'Tech Support Nightmares',
    speaker: 'Roy Trenneman',
    role: 'IT Specialist',
    duration: '18:50',
    listens: '65.2K listens',
    timeAgo: '6 months ago',
    thumbnail: thumb3,
    category: 'comedy',
    verified: true,
  },
  {
    id: 'pe-28',
    title: 'Introduction to Astrophysics and Black Holes',
    speaker: 'Dr. Sarah Webb',
    role: 'Astrophysicist',
    duration: '59:15',
    listens: '38.7K listens',
    timeAgo: '6 months ago',
    thumbnail: thumb4,
    category: 'education',
    verified: true,
  },
  {
    id: 'pe-29',
    title: 'HIIT vs Steady State Cardio: The Verdict',
    speaker: 'Marcus Johnson',
    role: 'Fitness Coach',
    duration: '26:30',
    listens: '54.1K listens',
    timeAgo: '7 months ago',
    thumbnail: thumb5,
    category: 'health',
    verified: true,
  },
  {
    id: 'pe-30',
    title: 'The Art of the Pitch: Securing Your First Million',
    speaker: 'Lisa Ray',
    role: 'Angel Investor',
    duration: '31:45',
    listens: '29.3K listens',
    timeAgo: '8 months ago',
    thumbnail: thumb6,
    category: 'business',
    verified: true,
  }
]