export const FIND_YOUR_PLACE_CONTENT = {
  sectionLabel: 'FIND YOUR PLACE IN N4RE',
  heading: 'How Can N4RE Help You?',
  description: 'Select your role and discover how N4RE can help you learn, connect and grow.',
  placeholder: 'Search your role...',
  inputPrefix: 'I am a',
}

export interface RoleModule {
  name: string
  comingSoon?: boolean
}

export interface RoleInfo {
  key: string
  label: string
  isPopular?: boolean
  helpTitle: string
  helpPoints: string[]
  ctaLabel: string
  relevantModules: RoleModule[]
}

export const ROLES: RoleInfo[] = [
  {
    key: 'builder',
    label: 'Builder / Developer',
    isPopular: true,
    helpTitle: 'How N4RE Helps Builders',
    helpPoints: [
      'Build visibility and establish your brand',
      'Discover vendors, agencies and service providers',
      'Find channel partners and explore partnerships',
      'Understand market trends and industry insights',
      'Conduct market research and make better decisions',
    ],
    ctaLabel: 'Join N4RE as Builder',
    relevantModules: [
      { name: 'Spotlight' },
      { name: 'Directory' },
      { name: 'Opportunities' },
      { name: 'Showcase', comingSoon: true },
      { name: 'Polls & Surveys', comingSoon: true },
    ],
  },
  {
    key: 'channel-partner',
    label: 'Channel Partner / Agent',
    isPopular: true,
    helpTitle: 'How N4RE Helps Channel Partners',
    helpPoints: [
      'Access builder inventory and new project launches',
      'Build your professional profile and credibility',
      'Connect with builders and explore business opportunities',
      'Stay updated with market trends and pricing',
      'Find hiring opportunities and grow your team',
    ],
    ctaLabel: 'Join N4RE as Channel Partner',
    relevantModules: [
      { name: 'Spotlight' },
      { name: 'Opportunities' },
      { name: 'Directory' },
      { name: 'City Inventory', comingSoon: true },
      { name: 'RED Expert' },
    ],
  },
  {
    key: 'sales-professional',
    label: 'Sales Professional',
    isPopular: true,
    helpTitle: 'How N4RE Helps Sales Professionals',
    helpPoints: [
      'Learn from top sales leaders and industry experts',
      'Discover new career opportunities and openings',
      'Build your professional brand and visibility',
      'Access sales training and skill development resources',
      'Network with industry professionals and peers',
    ],
    ctaLabel: 'Join N4RE as Sales Professional',
    relevantModules: [
      { name: 'RED Expert' },
      { name: 'Opportunities' },
      { name: 'Learn', comingSoon: true },
      { name: 'Spotlight' },
      { name: 'Directory' },
    ],
  },
  {
    key: 'marketing-professional',
    label: 'Marketing Professional',
    isPopular: true,
    helpTitle: 'How N4RE Helps Marketing Professionals',
    helpPoints: [
      'Showcase your work and build authority',
      'Find real estate clients and projects',
      'Learn the latest marketing trends in real estate',
      'Connect with builders, agencies and professionals',
      'Discover collaboration and freelance opportunities',
    ],
    ctaLabel: 'Join N4RE as Marketing Professional',
    relevantModules: [
      { name: 'Spotlight' },
      { name: 'Opportunities' },
      { name: 'Directory' },
      { name: 'Showcase', comingSoon: true },
      { name: 'RED Expert' },
    ],
  },
  {
    key: 'crm-professional',
    label: 'CRM Professional',
    isPopular: true,
    helpTitle: 'How N4RE Helps CRM Professionals',
    helpPoints: [
      'Demonstrate your CRM solutions to builders',
      'Connect with decision makers in real estate',
      'Understand pain points and market needs',
      'Generate leads and grow your customer base',
      'Build thought leadership in real estate tech',
    ],
    ctaLabel: 'Join N4RE as CRM Professional',
    relevantModules: [
      { name: 'Directory' },
      { name: 'Showcase', comingSoon: true },
      { name: 'Opportunities' },
      { name: 'Spotlight' },
      { name: 'RED Expert' },
    ],
  },
  {
    key: 'interior-designer',
    label: 'Interior Designer',
    isPopular: true,
    helpTitle: 'How N4RE Helps Interior Designers',
    helpPoints: [
      'Showcase your portfolio and design projects',
      'Connect with builders and property buyers',
      'Find collaboration opportunities with architects',
      'Build your brand in the real estate ecosystem',
      'Access new client leads and project requirements',
    ],
    ctaLabel: 'Join N4RE as Interior Designer',
    relevantModules: [
      { name: 'Spotlight' },
      { name: 'Directory' },
      { name: 'Opportunities' },
      { name: 'Showcase', comingSoon: true },
      { name: 'RED Expert' },
    ],
  },
  {
    key: 'fresher',
    label: 'Fresher / Student',
    isPopular: true,
    helpTitle: 'How N4RE Helps Freshers',
    helpPoints: [
      'Explore career opportunities in real estate',
      'Learn from industry experts and professionals',
      'Build your professional network from scratch',
      'Access training and skill development resources',
      'Understand different roles and career paths',
    ],
    ctaLabel: 'Join N4RE as Fresher',
    relevantModules: [
      { name: 'Opportunities' },
      { name: 'Learn', comingSoon: true },
      { name: 'RED Expert' },
      { name: 'Directory' },
      { name: 'Spotlight' },
    ],
  },
  {
    key: 'pre-sales',
    label: 'Pre-Sales Professional',
    helpTitle: 'How N4RE Helps Pre-Sales Professionals',
    helpPoints: [
      'Stay updated with project launches and inventory',
      'Learn from pre-sales experts and leaders',
      'Discover career growth opportunities',
      'Access industry insights and market data',
      'Network with builders and channel partners',
    ],
    ctaLabel: 'Join N4RE as Pre-Sales Professional',
    relevantModules: [
      { name: 'Opportunities' },
      { name: 'City Inventory', comingSoon: true },
      { name: 'RED Expert' },
      { name: 'Spotlight' },
      { name: 'Directory' },
    ],
  },
  {
    key: 'hr-professional',
    label: 'HR Professional',
    helpTitle: 'How N4RE Helps HR Professionals',
    helpPoints: [
      'Post job openings and find talent',
      'Connect with real estate professionals across roles',
      'Understand industry salary trends and benchmarks',
      'Build employer branding for your organization',
      'Access a talent pool of real estate professionals',
    ],
    ctaLabel: 'Join N4RE as HR Professional',
    relevantModules: [
      { name: 'Opportunities' },
      { name: 'Directory' },
      { name: 'Polls & Surveys', comingSoon: true },
      { name: 'Spotlight' },
      { name: 'RED Expert' },
    ],
  },
  {
    key: 'banking-professional',
    label: 'Banking Professional',
    isPopular: true,
    helpTitle: 'How N4RE Helps Banking Professionals',
    helpPoints: [
      'Connect with builders and channel partners for loan leads',
      'Build your professional brand in real estate finance',
      'Stay updated with real estate market trends',
      'Discover business development opportunities',
      'Network with industry professionals',
    ],
    ctaLabel: 'Join N4RE as Banking Professional',
    relevantModules: [
      { name: 'Directory' },
      { name: 'Opportunities' },
      { name: 'RED Expert' },
      { name: 'Spotlight' },
      { name: 'City Inventory', comingSoon: true },
    ],
  },
  {
    key: 'freelance-cp',
    label: 'Freelance Channel Partner',
    helpTitle: 'How N4RE Helps Freelance CPs',
    helpPoints: [
      'Access builder inventory and commission structures',
      'Build credibility and professional visibility',
      'Find collaboration opportunities with other partners',
      'Stay updated with new project launches',
      'Grow your independent business network',
    ],
    ctaLabel: 'Join N4RE as Freelance CP',
    relevantModules: [
      { name: 'Opportunities' },
      { name: 'City Inventory', comingSoon: true },
      { name: 'Directory' },
      { name: 'Spotlight' },
      { name: 'RED Expert' },
    ],
  },
  {
    key: 'investor',
    label: 'Investor / Inventory Owner',
    helpTitle: 'How N4RE Helps Investors',
    helpPoints: [
      'Discover investment opportunities across Hyderabad',
      'Access market intelligence and pricing trends',
      'Connect with builders, agents and professionals',
      'List your inventory and find buyers/tenants',
      'Stay informed about upcoming projects and launches',
    ],
    ctaLabel: 'Join N4RE as Investor',
    relevantModules: [
      { name: 'City Inventory', comingSoon: true },
      { name: 'Directory' },
      { name: 'Spotlight' },
      { name: 'Opportunities' },
      { name: 'Polls & Surveys', comingSoon: true },
    ],
  },
  {
    key: 'architect',
    label: 'Architect',
    helpTitle: 'How N4RE Helps Architects',
    helpPoints: [
      'Showcase your architectural projects and designs',
      'Connect with builders, developers and clients',
      'Find collaboration opportunities with interior designers',
      'Build thought leadership in architecture',
      'Discover project opportunities and RFPs',
    ],
    ctaLabel: 'Join N4RE as Architect',
    relevantModules: [
      { name: 'Spotlight' },
      { name: 'Directory' },
      { name: 'Opportunities' },
      { name: 'Showcase', comingSoon: true },
      { name: 'RED Expert' },
    ],
  },
  {
    key: 'legal-consultant',
    label: 'Legal Consultant',
    helpTitle: 'How N4RE Helps Legal Consultants',
    helpPoints: [
      'Build your brand as a real estate legal expert',
      'Connect with builders and developers for retainership',
      'Discover legal advisory opportunities',
      'Share knowledge and build authority',
      'Network with industry professionals',
    ],
    ctaLabel: 'Join N4RE as Legal Consultant',
    relevantModules: [
      { name: 'Directory' },
      { name: 'Opportunities' },
      { name: 'RED Expert' },
      { name: 'Spotlight' },
      { name: 'Showcase', comingSoon: true },
    ],
  },
  {
    key: 'marketing-agency',
    label: 'Marketing Agency',
    helpTitle: 'How N4RE Helps Marketing Agencies',
    helpPoints: [
      'Showcase your agency portfolio and case studies',
      'Connect with real estate builders as clients',
      'Find sub-contracting and collaboration opportunities',
      'Build authority through content and thought leadership',
      'Generate leads and grow your client base',
    ],
    ctaLabel: 'Join N4RE as Marketing Agency',
    relevantModules: [
      { name: 'Directory' },
      { name: 'Showcase', comingSoon: true },
      { name: 'Opportunities' },
      { name: 'Spotlight' },
      { name: 'RED Expert' },
    ],
  },
  {
    key: 'crm-provider',
    label: 'CRM Provider',
    helpTitle: 'How N4RE Helps CRM Providers',
    helpPoints: [
      'Demo your CRM solution to real estate companies',
      'Connect with builders and channel partner firms',
      'Understand industry-specific requirements',
      'Generate qualified leads for your product',
      'Build credibility through expert content',
    ],
    ctaLabel: 'Join N4RE as CRM Provider',
    relevantModules: [
      { name: 'Showcase', comingSoon: true },
      { name: 'Directory' },
      { name: 'Opportunities' },
      { name: 'Spotlight' },
      { name: 'RED Expert' },
    ],
  },
  {
    key: 'influencer',
    label: 'Influencer',
    isPopular: true,
    helpTitle: 'How N4RE Helps Influencers',
    helpPoints: [
      'Grow your audience in the real estate niche',
      'Collaborate with builders and brands',
      'Create sponsored content and partnerships',
      'Build authority as a real estate influencer',
      'Access exclusive industry events and interviews',
    ],
    ctaLabel: 'Join N4RE as Influencer',
    relevantModules: [
      { name: 'Spotlight' },
      { name: 'RED Expert' },
      { name: 'Opportunities' },
      { name: 'Directory' },
      { name: 'Showcase', comingSoon: true },
    ],
  },
  {
    key: 'trainer',
    label: 'Trainer',
    isPopular: true,
    helpTitle: 'How N4RE Helps Trainers',
    helpPoints: [
      'Reach real estate professionals for your courses',
      'Build your trainer profile and credibility',
      'Create and sell structured learning content',
      'Collaborate with organizations for corporate training',
      'Grow your community of learners',
    ],
    ctaLabel: 'Join N4RE as Trainer',
    relevantModules: [
      { name: 'Learn', comingSoon: true },
      { name: 'RED Expert' },
      { name: 'Spotlight' },
      { name: 'Directory' },
      { name: 'Showcase', comingSoon: true },
    ],
  },
  {
    key: 'technology-provider',
    label: 'Technology Provider',
    helpTitle: 'How N4RE Helps Technology Providers',
    helpPoints: [
      'Showcase your proptech solutions',
      'Connect with real estate companies for partnerships',
      'Understand technology needs of the industry',
      'Generate leads through demos and presentations',
      'Build thought leadership in proptech',
    ],
    ctaLabel: 'Join N4RE as Technology Provider',
    relevantModules: [
      { name: 'Showcase', comingSoon: true },
      { name: 'Directory' },
      { name: 'Opportunities' },
      { name: 'Spotlight' },
      { name: 'RED Expert' },
    ],
  },
  {
    key: 'home-inspection',
    label: 'Home Inspection Expert',
    helpTitle: 'How N4RE Helps Home Inspection Experts',
    helpPoints: [
      'List your services and build professional visibility',
      'Connect with builders, agents and home buyers',
      'Discover service requirement opportunities',
      'Build trust through verified profiles',
      'Grow your client base in Hyderabad',
    ],
    ctaLabel: 'Join N4RE as Home Inspector',
    relevantModules: [
      { name: 'Directory' },
      { name: 'Opportunities' },
      { name: 'Spotlight' },
      { name: 'Showcase', comingSoon: true },
      { name: 'RED Expert' },
    ],
  },
  {
    key: 'packers-movers',
    label: 'Packers & Movers',
    helpTitle: 'How N4RE Helps Packers & Movers',
    helpPoints: [
      'List your services for real estate professionals',
      'Connect with agents and property managers',
      'Find service opportunities and referrals',
      'Build your brand in the ecosystem',
      'Grow your business through verified presence',
    ],
    ctaLabel: 'Join N4RE as Packers & Movers',
    relevantModules: [
      { name: 'Directory' },
      { name: 'Opportunities' },
      { name: 'Spotlight' },
      { name: 'Showcase', comingSoon: true },
    ],
  },
  {
    key: 'others',
    label: 'Others',
    helpTitle: 'How N4RE Helps You',
    helpPoints: [
      'Discover your place in the real estate ecosystem',
      'Connect with professionals across all domains',
      'Find opportunities tailored to your expertise',
      'Build visibility and grow your network',
      'Learn from industry experts and leaders',
    ],
    ctaLabel: 'Join N4RE',
    relevantModules: [
      { name: 'Spotlight' },
      { name: 'Directory' },
      { name: 'Opportunities' },
      { name: 'RED Expert' },
      { name: 'Learn', comingSoon: true },
    ],
  },
]

export const POPULAR_ROLES = ROLES.filter((r) => r.isPopular)
