import type React from 'react'
import GridViewIcon from '@mui/icons-material/GridView'
import PersonSearchIcon from '@mui/icons-material/PersonSearch'
import SearchIcon from '@mui/icons-material/Search'
import BusinessCenterIcon from '@mui/icons-material/BusinessCenter'
import MenuBookIcon from '@mui/icons-material/MenuBook'

export interface FilterTab {
  key: string
  label: string
  Icon: React.ElementType
  color: string
}

const TAB_COLOR = '#6B7280'

export const FILTER_TABS: FilterTab[] = [
  { key: 'all', label: 'All', Icon: GridViewIcon, color: TAB_COLOR },
  { key: 'hiring', label: 'Hiring', Icon: PersonSearchIcon, color: TAB_COLOR },
  { key: 'lookingFor', label: 'Looking For', Icon: SearchIcon, color: TAB_COLOR },
  { key: 'offerings', label: 'Offerings', Icon: BusinessCenterIcon, color: TAB_COLOR },
  { key: 'resources', label: 'Resources', Icon: MenuBookIcon, color: TAB_COLOR },
]

export interface ActivityItem {
  id: string
  company: string
  title: string
  tag: string
  tagColor: string
  tagBg: string
  detail: string
  logoText: string
  logoBg: string
  logoColor: string
  verified: boolean
  cardBg?: string
  logoImg?: string
  salary: string
  location: string
  type: string
  skills: string[]
  description: string
  applicants: number
  views: number
  postedAgo: string
  hiringBadge: boolean
}

export interface TopCompany {
  name: string
  logoText: string
  logoBg: string
  logoColor: string
  logoImg?: string
  openings: number
}

export interface PopularCategory {
  name: string
  jobCount: string
  color: string
  bgColor: string
}

export interface TrendingSkill {
  label: string
}

export const TOP_COMPANIES: TopCompany[] = [
  { name: 'ABC Realty', logoText: 'ABC\nREALTY', logoBg: '#111827', logoColor: '#D1D5DB', openings: 32 },
  { name: 'Prime Infra', logoText: 'PRIME\n INFRA', logoBg: '#F3F4F6', logoColor: '#111827', openings: 18 },
  { name: 'BuildTech Solutions', logoText: '', logoBg: '#F3F4F6', logoColor: '#111827', logoImg: 'https://i.pravatar.cc/150?u=bts', openings: 12 },
  { name: 'GreenSpace Developers', logoText: 'GS\nDEV', logoBg: '#059669', logoColor: '#FFFFFF', openings: 10 },
  { name: 'UrbanNest Properties', logoText: 'UN', logoBg: '#7C3AED', logoColor: '#FFFFFF', openings: 8 },
]

export const POPULAR_CATEGORIES: PopularCategory[] = [
  { name: 'Sales', jobCount: '120+ Jobs', color: '#E91E8C', bgColor: '#FFF0F6' },
  { name: 'Marketing', jobCount: '95+ Jobs', color: '#3B82F6', bgColor: '#EFF6FF' },
  { name: 'Real Estate', jobCount: '80+ Jobs', color: '#7C3AED', bgColor: '#F5F3FF' },
  { name: 'Finance', jobCount: '65+ Jobs', color: '#10B981', bgColor: '#ECFDF5' },
  { name: 'Design', jobCount: '45+ Jobs', color: '#F59E0B', bgColor: '#FFFBEB' },
  { name: 'Operations', jobCount: '40+ Jobs', color: '#EF4444', bgColor: '#FEF2F2' },
]

export const TRENDING_SKILLS: TrendingSkill[] = [
  { label: 'Sales' },
  { label: 'Negotiation' },
  { label: 'Business Development' },
  { label: 'CRM' },
  { label: 'Lead Generation' },
  { label: 'Communication' },
  { label: 'Marketing Strategy' },
  { label: 'Digital Marketing' },
  { label: 'Team Leadership' },
  { label: 'Client Relationship' },
]

export const ACTIVITY_ITEMS: ActivityItem[] = [
  {
    id: 'act-1',
    company: 'ABC Realty',
    title: 'Sales Manager Required',
    tag: 'Sales',
    tagColor: '#E91E8C',
    tagBg: '#FCE7F3',
    detail: '₹8 - 12 LPA',
    logoText: 'ABC\nREALTY',
    logoBg: '#111827',
    logoColor: '#D1D5DB',
    verified: true,
    cardBg: '#FFFFFF',
    salary: '₹8 – 12 LPA',
    location: 'Bangalore, India',
    type: 'Full Time',
    skills: ['Residential Sales', '3+ Years Exp', 'Team Handling'],
    description: 'We are looking for a motivated Sales Manager to lead our residential sales team and drive performance. The ideal candidate should have strong leadership skills and a proven track record in real estate sales.',
    applicants: 12,
    views: 156,
    postedAgo: 'Posted 2 days ago',
    hiringBadge: true,
  },
  {
    id: 'act-2',
    company: 'Prime Infra',
    title: 'Looking for Lead Generation Agency',
    tag: 'Marketing',
    tagColor: '#3B82F6',
    tagBg: '#EFF6FF',
    detail: '₹50,000 / Month',
    logoText: 'PRIME\n INFRA',
    logoBg: '#F3F4F6',
    logoColor: '#111827',
    verified: true,
    cardBg: '#FFFFFF',
    salary: '₹50,000 / Month',
    location: 'Bangalore, India',
    type: 'Full Time',
    skills: ['Marketing', 'Agency', 'Lead Generation'],
    description: 'We are looking for a reliable lead generation agency to help us scale our inbound pipeline for residential projects across South India.',
    applicants: 8,
    views: 94,
    postedAgo: 'Posted 3 days ago',
    hiringBadge: false,
  },
  {
    id: 'act-3',
    company: 'BuildTech Solutions',
    title: 'Business Development Manager',
    tag: 'Sales',
    tagColor: '#E91E8C',
    tagBg: '#FCE7F3',
    detail: '₹10 - 15 LPA',
    logoText: '',
    logoBg: '#F3F4F6',
    logoColor: '#111827',
    verified: true,
    cardBg: '#FFFFFF',
    logoImg: 'https://i.pravatar.cc/150?u=bts',
    salary: '₹10 – 15 LPA',
    location: 'Pune, India',
    type: 'Full Time',
    skills: ['B2B Sales', '5+ Years Exp', 'Client Acquisition'],
    description: 'BuildTech Solutions is hiring a Business Development Manager to drive growth and establish new partnerships in the construction technology space.',
    applicants: 15,
    views: 203,
    postedAgo: 'Posted 1 day ago',
    hiringBadge: true,
  },
  {
    id: 'act-4',
    company: 'Rahul Marketing Studio',
    title: 'Digital Marketing Services',
    tag: 'Marketing',
    tagColor: '#10B981',
    tagBg: '#D1FAE5',
    detail: 'Starting ₹25,000',
    logoText: '',
    logoBg: '#F3F4F6',
    logoColor: '#111827',
    verified: true,
    cardBg: '#FFFFFF',
    logoImg: 'https://i.pravatar.cc/150?u=rms',
    salary: 'Starting ₹25,000',
    location: 'Mumbai, India',
    type: 'Freelance',
    skills: ['SEO', 'Social Media', 'Content Strategy'],
    description: 'Full-stack digital marketing services including SEO, social media management, and content strategy for real estate developers.',
    applicants: 5,
    views: 78,
    postedAgo: 'Posted 4 days ago',
    hiringBadge: false,
  },
  {
    id: 'act-5',
    company: 'Design Space Studio',
    title: 'Interior Design Services',
    tag: 'Design',
    tagColor: '#10B981',
    tagBg: '#D1FAE5',
    detail: 'Starting ₹40,000',
    logoText: 'DESIGN\nSPACE',
    logoBg: '#F3F4F6',
    logoColor: '#111827',
    verified: true,
    cardBg: '#FFFFFF',
    salary: 'Starting ₹40,000',
    location: 'Delhi, India',
    type: 'Contract',
    skills: ['Interior Design', 'AutoCAD', '3D Rendering'],
    description: 'Offering premium interior design services for commercial and residential properties. Expertise in modern minimalist and luxury design aesthetics.',
    applicants: 9,
    views: 112,
    postedAgo: 'Posted 5 days ago',
    hiringBadge: false,
  },
  {
    id: 'act-6',
    company: 'Yardstack Insights',
    title: 'Residential Market Report 2026',
    tag: 'Report',
    tagColor: '#F59E0B',
    tagBg: '#FEF3C7',
    detail: 'Free Download',
    logoText: 'Y',
    logoBg: '#F3F4F6',
    logoColor: '#D946EF',
    verified: true,
    cardBg: '#FFFFFF',
    salary: 'Free Download',
    location: 'Pan India',
    type: 'Resource',
    skills: ['Market Analysis', 'Research', 'Real Estate'],
    description: 'Comprehensive residential market report covering trends, pricing analysis, and growth forecasts for major Indian cities in 2026.',
    applicants: 0,
    views: 340,
    postedAgo: 'Posted 1 week ago',
    hiringBadge: false,
  },
  {
    id: 'act-7',
    company: 'Happy Homes',
    title: 'Architect Required',
    tag: 'Design',
    tagColor: '#E91E8C',
    tagBg: '#FCE7F3',
    detail: '₹6 - 9 LPA',
    logoText: 'HH\nHOMES',
    logoBg: '#F3F4F6',
    logoColor: '#111827',
    verified: true,
    cardBg: '#FFFFFF',
    salary: '₹6 – 9 LPA',
    location: 'Hyderabad, India',
    type: 'Full Time',
    skills: ['Architecture', 'Revit', 'Project Management'],
    description: 'Happy Homes is looking for a talented architect to join our design team and work on upcoming luxury residential projects.',
    applicants: 7,
    views: 89,
    postedAgo: 'Posted 3 days ago',
    hiringBadge: true,
  },
  {
    id: 'act-8',
    company: 'TechRecruit Ltd',
    title: 'Senior Frontend Developer',
    tag: 'Technology',
    tagColor: '#E91E8C',
    tagBg: '#FCE7F3',
    detail: '₹15 - 20 LPA',
    logoText: 'TECH\nREC',
    logoBg: '#2563EB',
    logoColor: '#FFFFFF',
    verified: true,
    cardBg: '#FFFFFF',
    salary: '₹15 – 20 LPA',
    location: 'Bangalore, India',
    type: 'Full Time',
    skills: ['React', 'TypeScript', 'System Design'],
    description: 'We are hiring a Senior Frontend Developer to build scalable property management tools using React and TypeScript.',
    applicants: 22,
    views: 287,
    postedAgo: 'Posted 12 hours ago',
    hiringBadge: true,
  },
  {
    id: 'act-9',
    company: 'Urban Builders',
    title: 'Looking for Legal Consultant',
    tag: 'Legal',
    tagColor: '#3B82F6',
    tagBg: '#EFF6FF',
    detail: 'Contractual',
    logoText: 'URBAN\nBUILD',
    logoBg: '#F3F4F6',
    logoColor: '#1F2937',
    verified: false,
    cardBg: '#FFFFFF',
    salary: 'Contractual',
    location: 'Chennai, India',
    type: 'Contract',
    skills: ['Real Estate Law', 'RERA Compliance', 'Documentation'],
    description: 'Seeking an experienced legal consultant for RERA compliance and property documentation for our upcoming projects.',
    applicants: 4,
    views: 56,
    postedAgo: 'Posted 5 days ago',
    hiringBadge: false,
  },
  {
    id: 'act-10',
    company: 'DataFlow Systems',
    title: 'Cloud Database Hosting',
    tag: 'Technology',
    tagColor: '#10B981',
    tagBg: '#D1FAE5',
    detail: 'Starting ₹10,000/mo',
    logoText: '',
    logoBg: '#111827',
    logoColor: '#FFFFFF',
    verified: true,
    cardBg: '#FFFFFF',
    logoImg: 'https://i.pravatar.cc/150?u=dataflow',
    salary: 'Starting ₹10,000/mo',
    location: 'Remote',
    type: 'Service',
    skills: ['Cloud Hosting', 'Database', 'SaaS'],
    description: 'Enterprise-grade cloud database hosting optimized for real estate CRM platforms with 99.9% uptime guarantee.',
    applicants: 0,
    views: 145,
    postedAgo: 'Posted 6 days ago',
    hiringBadge: false,
  },
  {
    id: 'act-11',
    company: 'HR Pro Connect',
    title: '2026 Salary Benchmark Guide',
    tag: 'HR',
    tagColor: '#F59E0B',
    tagBg: '#FEF3C7',
    detail: 'Free Access',
    logoText: 'HR\nPRO',
    logoBg: '#F59E0B',
    logoColor: '#FFFFFF',
    verified: true,
    cardBg: '#FFFFFF',
    salary: 'Free Access',
    location: 'Pan India',
    type: 'Resource',
    skills: ['HR', 'Salary Data', 'Benchmarking'],
    description: 'Industry-wide salary benchmark guide for real estate professionals covering all major roles and metros in India.',
    applicants: 0,
    views: 420,
    postedAgo: 'Posted 1 week ago',
    hiringBadge: false,
  },
  {
    id: 'act-12',
    company: 'Skyline Construction',
    title: 'Project Manager Required',
    tag: 'Management',
    tagColor: '#E91E8C',
    tagBg: '#FCE7F3',
    detail: '₹12 - 18 LPA',
    logoText: 'SKY\nLINE',
    logoBg: '#047857',
    logoColor: '#FFFFFF',
    verified: true,
    cardBg: '#FFFFFF',
    salary: '₹12 – 18 LPA',
    location: 'Gurgaon, India',
    type: 'Full Time',
    skills: ['Project Management', 'Construction', 'Scheduling'],
    description: 'Seeking an experienced Project Manager to oversee large-scale residential construction projects from planning to handover.',
    applicants: 18,
    views: 234,
    postedAgo: 'Posted 2 days ago',
    hiringBadge: true,
  },
  {
    id: 'act-13',
    company: 'CleanSweep Services',
    title: 'Corporate Cleaning Solutions',
    tag: 'Facility',
    tagColor: '#10B981',
    tagBg: '#D1FAE5',
    detail: 'Custom Pricing',
    logoText: 'CLEAN\nSWEEP',
    logoBg: '#EFF6FF',
    logoColor: '#1D4ED8',
    verified: true,
    cardBg: '#FFFFFF',
    salary: 'Custom Pricing',
    location: 'Multiple Cities',
    type: 'Service',
    skills: ['Facility Management', 'Housekeeping', 'Maintenance'],
    description: 'Professional corporate cleaning and facility management solutions for commercial real estate properties.',
    applicants: 3,
    views: 67,
    postedAgo: 'Posted 4 days ago',
    hiringBadge: false,
  },
  {
    id: 'act-14',
    company: 'Visionary Designs',
    title: 'Looking for 3D Render Artist',
    tag: 'Design',
    tagColor: '#3B82F6',
    tagBg: '#EFF6FF',
    detail: 'Per Project Basis',
    logoText: 'VIS\nDES',
    logoBg: '#111827',
    logoColor: '#E5E7EB',
    verified: false,
    cardBg: '#FFFFFF',
    salary: 'Per Project Basis',
    location: 'Remote',
    type: 'Freelance',
    skills: ['3D Rendering', 'V-Ray', 'SketchUp'],
    description: 'Looking for skilled 3D render artists to create photorealistic architectural visualizations for luxury real estate projects.',
    applicants: 11,
    views: 178,
    postedAgo: 'Posted 3 days ago',
    hiringBadge: false,
  },
  {
    id: 'act-15',
    company: 'FinancePlus',
    title: 'Tax Compliance Checklist Q2',
    tag: 'Finance',
    tagColor: '#F59E0B',
    tagBg: '#FEF3C7',
    detail: 'Download PDF',
    logoText: 'FIN+',
    logoBg: '#F3F4F6',
    logoColor: '#059669',
    verified: true,
    cardBg: '#FFFFFF',
    salary: 'Free Download',
    location: 'Pan India',
    type: 'Resource',
    skills: ['Tax', 'Compliance', 'Finance'],
    description: 'Essential tax compliance checklist for real estate developers and agents for Q2 2026 filing deadlines.',
    applicants: 0,
    views: 256,
    postedAgo: 'Posted 1 week ago',
    hiringBadge: false,
  },
  {
    id: 'act-16',
    company: 'Global Logistics',
    title: 'Warehouse Manager Needed',
    tag: 'Logistics',
    tagColor: '#E91E8C',
    tagBg: '#FCE7F3',
    detail: '₹5 - 8 LPA',
    logoText: 'GLOBE\nLOG',
    logoBg: '#4B5563',
    logoColor: '#FFFFFF',
    verified: true,
    cardBg: '#FFFFFF',
    salary: '₹5 – 8 LPA',
    location: 'Ahmedabad, India',
    type: 'Full Time',
    skills: ['Warehouse Management', 'Inventory', 'Logistics'],
    description: 'Managing warehouse operations for construction materials supply chain across Western India.',
    applicants: 6,
    views: 89,
    postedAgo: 'Posted 4 days ago',
    hiringBadge: true,
  },
  {
    id: 'act-17',
    company: 'NextGen AI',
    title: 'AI Integration Services',
    tag: 'Technology',
    tagColor: '#10B981',
    tagBg: '#D1FAE5',
    detail: 'Starting ₹1,00,000',
    logoText: '',
    logoBg: '#F3F4F6',
    logoColor: '#111827',
    verified: true,
    cardBg: '#FFFFFF',
    logoImg: 'https://i.pravatar.cc/150?u=nextgen',
    salary: 'Starting ₹1,00,000',
    location: 'Bangalore, India',
    type: 'Service',
    skills: ['AI/ML', 'PropTech', 'Automation'],
    description: 'AI-powered solutions for real estate including automated property valuation, lead scoring, and chatbot integration.',
    applicants: 0,
    views: 312,
    postedAgo: 'Posted 2 days ago',
    hiringBadge: false,
  },
  {
    id: 'act-18',
    company: 'Metro Retail',
    title: 'Looking for Inventory Software',
    tag: 'Technology',
    tagColor: '#3B82F6',
    tagBg: '#EFF6FF',
    detail: '₹20,000 - ₹50,000',
    logoText: 'METRO\nRETAIL',
    logoBg: '#FEE2E2',
    logoColor: '#B91C1C',
    verified: false,
    cardBg: '#FFFFFF',
    salary: '₹20,000 – ₹50,000',
    location: 'Kolkata, India',
    type: 'Service',
    skills: ['ERP', 'Inventory', 'Software'],
    description: 'Seeking inventory management software solutions for our retail construction material outlets across East India.',
    applicants: 7,
    views: 98,
    postedAgo: 'Posted 5 days ago',
    hiringBadge: false,
  },
  {
    id: 'act-19',
    company: 'Creative Sparks',
    title: 'Social Media Content Calendar',
    tag: 'Resource',
    tagColor: '#F59E0B',
    tagBg: '#FEF3C7',
    detail: 'Free Excel Template',
    logoText: 'CS',
    logoBg: '#F3F4F6',
    logoColor: '#D97706',
    verified: true,
    cardBg: '#FFFFFF',
    salary: 'Free',
    location: 'Pan India',
    type: 'Resource',
    skills: ['Social Media', 'Content Planning', 'Templates'],
    description: 'Ready-to-use social media content calendar template designed specifically for real estate marketing teams.',
    applicants: 0,
    views: 189,
    postedAgo: 'Posted 1 week ago',
    hiringBadge: false,
  },
  {
    id: 'act-20',
    company: 'Apex Consulting',
    title: 'Business Strategy Consultation',
    tag: 'Consulting',
    tagColor: '#10B981',
    tagBg: '#D1FAE5',
    detail: '₹5,000 / Hour',
    logoText: 'APEX\nCONS',
    logoBg: '#1E3A8A',
    logoColor: '#FFFFFF',
    verified: true,
    cardBg: '#FFFFFF',
    salary: '₹5,000 / Hour',
    location: 'Mumbai, India',
    type: 'Consulting',
    skills: ['Strategy', 'Growth', 'Market Entry'],
    description: 'Expert business strategy consulting for real estate developers looking to expand into new markets and segments.',
    applicants: 2,
    views: 134,
    postedAgo: 'Posted 3 days ago',
    hiringBadge: false,
  },
  {
    id: 'act-21',
    company: 'BlueWave Marine',
    title: 'Marine Engineer Required',
    tag: 'Engineering',
    tagColor: '#E91E8C',
    tagBg: '#FCE7F3',
    detail: '₹14 - 22 LPA',
    logoText: 'BLUE\nWAVE',
    logoBg: '#0284C7',
    logoColor: '#FFFFFF',
    verified: true,
    cardBg: '#FFFFFF',
    salary: '₹14 – 22 LPA',
    location: 'Kochi, India',
    type: 'Full Time',
    skills: ['Marine Engineering', 'Coastal Development', 'Structural'],
    description: 'Hiring experienced marine engineers for waterfront and coastal real estate development projects.',
    applicants: 3,
    views: 67,
    postedAgo: 'Posted 6 days ago',
    hiringBadge: true,
  },
  {
    id: 'act-22',
    company: 'EcoPack India',
    title: 'Looking for Raw Material Supplier',
    tag: 'Manufacturing',
    tagColor: '#3B82F6',
    tagBg: '#EFF6FF',
    detail: 'Bulk Orders',
    logoText: '',
    logoBg: '#F3F4F6',
    logoColor: '#111827',
    verified: true,
    cardBg: '#FFFFFF',
    logoImg: 'https://i.pravatar.cc/150?u=ecopack',
    salary: 'Bulk Orders',
    location: 'Surat, India',
    type: 'Supply',
    skills: ['Raw Materials', 'Bulk Supply', 'Eco-Friendly'],
    description: 'Looking for sustainable raw material suppliers for eco-friendly packaging used in construction materials.',
    applicants: 5,
    views: 76,
    postedAgo: 'Posted 4 days ago',
    hiringBadge: false,
  },
  {
    id: 'act-23',
    company: 'Legal Minds',
    title: 'Corporate Contract Drafting',
    tag: 'Legal',
    tagColor: '#10B981',
    tagBg: '#D1FAE5',
    detail: 'Starting ₹15,000',
    logoText: 'LEGAL\nMINDS',
    logoBg: '#111827',
    logoColor: '#D1D5DB',
    verified: true,
    cardBg: '#FFFFFF',
    salary: 'Starting ₹15,000',
    location: 'Delhi, India',
    type: 'Service',
    skills: ['Contract Law', 'Corporate', 'Drafting'],
    description: 'Professional contract drafting services for real estate transactions, joint ventures, and corporate agreements.',
    applicants: 6,
    views: 102,
    postedAgo: 'Posted 5 days ago',
    hiringBadge: false,
  },
  {
    id: 'act-24',
    company: 'HealthPlus',
    title: 'Workplace Wellness Guide',
    tag: 'HR',
    tagColor: '#F59E0B',
    tagBg: '#FEF3C7',
    detail: 'Free eBook',
    logoText: 'H+',
    logoBg: '#10B981',
    logoColor: '#FFFFFF',
    verified: true,
    cardBg: '#FFFFFF',
    salary: 'Free',
    location: 'Pan India',
    type: 'Resource',
    skills: ['Wellness', 'HR', 'Employee Health'],
    description: 'Comprehensive workplace wellness guide tailored for real estate firms to boost employee productivity and satisfaction.',
    applicants: 0,
    views: 198,
    postedAgo: 'Posted 1 week ago',
    hiringBadge: false,
  },
  {
    id: 'act-25',
    company: 'Quantum Finance',
    title: 'Investment Analyst Needed',
    tag: 'Finance',
    tagColor: '#E91E8C',
    tagBg: '#FCE7F3',
    detail: '₹10 - 15 LPA',
    logoText: 'Q\nFIN',
    logoBg: '#F3F4F6',
    logoColor: '#4338CA',
    verified: true,
    cardBg: '#FFFFFF',
    salary: '₹10 – 15 LPA',
    location: 'Mumbai, India',
    type: 'Full Time',
    skills: ['Investment Analysis', 'Financial Modeling', 'Real Estate'],
    description: 'Quantum Finance is hiring an Investment Analyst to evaluate real estate investment opportunities and portfolio performance.',
    applicants: 14,
    views: 245,
    postedAgo: 'Posted 1 day ago',
    hiringBadge: true,
  },
]