import type React from 'react'
import GridViewIcon from '@mui/icons-material/GridView'
import PersonSearchIcon from '@mui/icons-material/PersonSearch'
import SearchIcon from '@mui/icons-material/Search'
import BusinessCenterIcon from '@mui/icons-material/BusinessCenter'
import MenuBookIcon from '@mui/icons-material/MenuBook'

export interface FilterTab {
  key: string
  label: string
  Icon: React.ElementType
  color: string
}

const TAB_COLOR = '#6B7280'

export const FILTER_TABS: FilterTab[] = [
  { key: 'all', label: 'All', Icon: GridViewIcon, color: TAB_COLOR },
  { key: 'hiring', label: 'Hiring', Icon: PersonSearchIcon, color: TAB_COLOR },
  { key: 'lookingFor', label: 'Looking For', Icon: SearchIcon, color: TAB_COLOR },
  { key: 'offerings', label: 'Offerings', Icon: BusinessCenterIcon, color: TAB_COLOR },
  { key: 'resources', label: 'Resources', Icon: MenuBookIcon, color: TAB_COLOR },
]

export interface ActivityItem {
  id: string
  company: string
  title: string
  tag: string
  tagColor: string
  tagBg: string
  detail: string
  logoText: string
  logoBg: string
  logoColor: string
  verified: boolean
  cardBg?: string
  logoImg?: string
}

export const ACTIVITY_ITEMS: ActivityItem[] = [
  {
    id: 'act-1',
    company: 'ABC Realty',
    title: 'Sales Manager Required',
    tag: 'Sales',
    tagColor: '#E91E8C',
    tagBg: '#FCE7F3',
    detail: '₹8 - 12 LPA',
    logoText: 'ABC\nREALTY',
    logoBg: '#111827',
    logoColor: '#D1D5DB',
    verified: true,
    cardBg: '#FFF5F8',
  },
  {
    id: 'act-2',
    company: 'Prime Infra',
    title: 'Looking for Lead Generation Agency',
    tag: 'Marketing',
    tagColor: '#3B82F6',
    tagBg: '#EFF6FF',
    detail: '₹50,000 / Month',
    logoText: 'PRIME\n INFRA',
    logoBg: '#F3F4F6',
    logoColor: '#111827',
    verified: true,
    cardBg: '#F4F8FF',
  },
  {
    id: 'act-3',
    company: 'BuildTech Solutions',
    title: 'Looking for CRM Software',
    tag: 'Technology',
    tagColor: '#3B82F6',
    tagBg: '#EFF6FF',
    detail: '₹30,000 - ₹60,000',
    logoText: '',
    logoBg: '#F3F4F6',
    logoColor: '#111827',
    verified: true,
    cardBg: '#F4F8FF',
    logoImg: 'https://i.pravatar.cc/150?u=bts',
  },
  {
    id: 'act-4',
    company: 'Rahul Marketing Studio',
    title: 'Digital Marketing Services',
    tag: 'Marketing',
    tagColor: '#10B981',
    tagBg: '#D1FAE5',
    detail: 'Starting ₹25,000',
    logoText: '',
    logoBg: '#F3F4F6',
    logoColor: '#111827',
    verified: true,
    cardBg: '#F0FDF4',
    logoImg: 'https://i.pravatar.cc/150?u=rms',
  },
  {
    id: 'act-5',
    company: 'Design Space Studio',
    title: 'Interior Design Services',
    tag: 'Design',
    tagColor: '#10B981',
    tagBg: '#D1FAE5',
    detail: 'Starting ₹40,000',
    logoText: 'DESIGN\nSPACE',
    logoBg: '#F3F4F6',
    logoColor: '#111827',
    verified: true,
    cardBg: '#F0FDF4',
  },
  {
    id: 'act-6',
    company: 'Yardstack Insights',
    title: 'Residential Market Report 2026',
    tag: 'Report',
    tagColor: '#F59E0B',
    tagBg: '#FEF3C7',
    detail: 'Free Download',
    logoText: 'Y',
    logoBg: '#F3F4F6',
    logoColor: '#D946EF',
    verified: true,
    cardBg: '#FFFBEB',
  },
  {
    id: 'act-7',
    company: 'Happy Homes',
    title: 'Architect Required',
    tag: 'Design',
    tagColor: '#E91E8C',
    tagBg: '#FCE7F3',
    detail: '₹6 - 9 LPA',
    logoText: 'HH\nHOMES',
    logoBg: '#F3F4F6',
    logoColor: '#111827',
    verified: true,
    cardBg: '#FFF5F8',
  },
  {
    id: 'act-8',
    company: 'TechRecruit Ltd',
    title: 'Senior Frontend Developer',
    tag: 'Technology',
    tagColor: '#E91E8C',
    tagBg: '#FCE7F3',
    detail: '₹15 - 20 LPA',
    logoText: 'TECH\nREC',
    logoBg: '#2563EB',
    logoColor: '#FFFFFF',
    verified: true,
    cardBg: '#FFF5F8',
  },
  {
    id: 'act-9',
    company: 'Urban Builders',
    title: 'Looking for Legal Consultant',
    tag: 'Legal',
    tagColor: '#3B82F6',
    tagBg: '#EFF6FF',
    detail: 'Contractual',
    logoText: 'URBAN\nBUILD',
    logoBg: '#F3F4F6',
    logoColor: '#1F2937',
    verified: false,
    cardBg: '#F4F8FF',
  },
  {
    id: 'act-10',
    company: 'DataFlow Systems',
    title: 'Cloud Database Hosting',
    tag: 'Technology',
    tagColor: '#10B981',
    tagBg: '#D1FAE5',
    detail: 'Starting ₹10,000/mo',
    logoText: '',
    logoBg: '#111827',
    logoColor: '#FFFFFF',
    verified: true,
    cardBg: '#F0FDF4',
    logoImg: 'https://i.pravatar.cc/150?u=dataflow',
  },
  {
    id: 'act-11',
    company: 'HR Pro Connect',
    title: '2026 Salary Benchmark Guide',
    tag: 'HR',
    tagColor: '#F59E0B',
    tagBg: '#FEF3C7',
    detail: 'Free Access',
    logoText: 'HR\nPRO',
    logoBg: '#F59E0B',
    logoColor: '#FFFFFF',
    verified: true,
    cardBg: '#FFFBEB',
  },
  {
    id: 'act-12',
    company: 'Skyline Construction',
    title: 'Project Manager Required',
    tag: 'Management',
    tagColor: '#E91E8C',
    tagBg: '#FCE7F3',
    detail: '₹12 - 18 LPA',
    logoText: 'SKY\nLINE',
    logoBg: '#047857',
    logoColor: '#FFFFFF',
    verified: true,
    cardBg: '#FFF5F8',
  },
  {
    id: 'act-13',
    company: 'CleanSweep Services',
    title: 'Corporate Cleaning Solutions',
    tag: 'Facility',
    tagColor: '#10B981',
    tagBg: '#D1FAE5',
    detail: 'Custom Pricing',
    logoText: 'CLEAN\nSWEEP',
    logoBg: '#EFF6FF',
    logoColor: '#1D4ED8',
    verified: true,
    cardBg: '#F0FDF4',
  },
  {
    id: 'act-14',
    company: 'Visionary Designs',
    title: 'Looking for 3D Render Artist',
    tag: 'Design',
    tagColor: '#3B82F6',
    tagBg: '#EFF6FF',
    detail: 'Per Project Basis',
    logoText: 'VIS\nDES',
    logoBg: '#111827',
    logoColor: '#E5E7EB',
    verified: false,
    cardBg: '#F4F8FF',
  },
  {
    id: 'act-15',
    company: 'FinancePlus',
    title: 'Tax Compliance Checklist Q2',
    tag: 'Finance',
    tagColor: '#F59E0B',
    tagBg: '#FEF3C7',
    detail: 'Download PDF',
    logoText: 'FIN+',
    logoBg: '#F3F4F6',
    logoColor: '#059669',
    verified: true,
    cardBg: '#FFFBEB',
  },
  {
    id: 'act-16',
    company: 'Global Logistics',
    title: 'Warehouse Manager Needed',
    tag: 'Logistics',
    tagColor: '#E91E8C',
    tagBg: '#FCE7F3',
    detail: '₹5 - 8 LPA',
    logoText: 'GLOBE\nLOG',
    logoBg: '#4B5563',
    logoColor: '#FFFFFF',
    verified: true,
    cardBg: '#FFF5F8',
  },
  {
    id: 'act-17',
    company: 'NextGen AI',
    title: 'AI Integration Services',
    tag: 'Technology',
    tagColor: '#10B981',
    tagBg: '#D1FAE5',
    detail: 'Starting ₹1,00,000',
    logoText: '',
    logoBg: '#F3F4F6',
    logoColor: '#111827',
    verified: true,
    cardBg: '#F0FDF4',
    logoImg: 'https://i.pravatar.cc/150?u=nextgen',
  },
  {
    id: 'act-18',
    company: 'Metro Retail',
    title: 'Looking for Inventory Software',
    tag: 'Technology',
    tagColor: '#3B82F6',
    tagBg: '#EFF6FF',
    detail: '₹20,000 - ₹50,000',
    logoText: 'METRO\nRETAIL',
    logoBg: '#FEE2E2',
    logoColor: '#B91C1C',
    verified: false,
    cardBg: '#F4F8FF',
  },
  {
    id: 'act-19',
    company: 'Creative Sparks',
    title: 'Social Media Content Calendar',
    tag: 'Resource',
    tagColor: '#F59E0B',
    tagBg: '#FEF3C7',
    detail: 'Free Excel Template',
    logoText: 'CS',
    logoBg: '#F3F4F6',
    logoColor: '#D97706',
    verified: true,
    cardBg: '#FFFBEB',
  },
  {
    id: 'act-20',
    company: 'Apex Consulting',
    title: 'Business Strategy Consultation',
    tag: 'Consulting',
    tagColor: '#10B981',
    tagBg: '#D1FAE5',
    detail: '₹5,000 / Hour',
    logoText: 'APEX\nCONS',
    logoBg: '#1E3A8A',
    logoColor: '#FFFFFF',
    verified: true,
    cardBg: '#F0FDF4',
  },
  {
    id: 'act-21',
    company: 'BlueWave Marine',
    title: 'Marine Engineer Required',
    tag: 'Engineering',
    tagColor: '#E91E8C',
    tagBg: '#FCE7F3',
    detail: '₹14 - 22 LPA',
    logoText: 'BLUE\nWAVE',
    logoBg: '#0284C7',
    logoColor: '#FFFFFF',
    verified: true,
    cardBg: '#FFF5F8',
  },
  {
    id: 'act-22',
    company: 'EcoPack India',
    title: 'Looking for Raw Material Supplier',
    tag: 'Manufacturing',
    tagColor: '#3B82F6',
    tagBg: '#EFF6FF',
    detail: 'Bulk Orders',
    logoText: '',
    logoBg: '#F3F4F6',
    logoColor: '#111827',
    verified: true,
    cardBg: '#F4F8FF',
    logoImg: 'https://i.pravatar.cc/150?u=ecopack',
  },
  {
    id: 'act-23',
    company: 'Legal Minds',
    title: 'Corporate Contract Drafting',
    tag: 'Legal',
    tagColor: '#10B981',
    tagBg: '#D1FAE5',
    detail: 'Starting ₹15,000',
    logoText: 'LEGAL\nMINDS',
    logoBg: '#111827',
    logoColor: '#D1D5DB',
    verified: true,
    cardBg: '#F0FDF4',
  },
  {
    id: 'act-24',
    company: 'HealthPlus',
    title: 'Workplace Wellness Guide',
    tag: 'HR',
    tagColor: '#F59E0B',
    tagBg: '#FEF3C7',
    detail: 'Free eBook',
    logoText: 'H+',
    logoBg: '#10B981',
    logoColor: '#FFFFFF',
    verified: true,
    cardBg: '#FFFBEB',
  },
  {
    id: 'act-25',
    company: 'Quantum Finance',
    title: 'Investment Analyst Needed',
    tag: 'Finance',
    tagColor: '#E91E8C',
    tagBg: '#FCE7F3',
    detail: '₹10 - 15 LPA',
    logoText: 'Q\nFIN',
    logoBg: '#F3F4F6',
    logoColor: '#4338CA',
    verified: true,
    cardBg: '#FFF5F8',
  },
]